
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: rtg
      POSTGRES_PASSWORD: rtg
      POSTGRES_DB: rtg
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rtg -d rtg"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: postgresql+psycopg://rtg:rtg@db:5432/rtg
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  pgdata: